Feed Adapter now supports short GUIDs for episode Guid Id's
RadioPublic/play.prx.org pull request #5
Opened 2016-12-28 21:48 UTC by alxjrvs

2016-12-28 22:29 UTC, alxjrvs commented
![](https://github.trello.services/images/mini-trello-icon.png) [FeedAdapter can accept encoded episode guid's](https://trello.com/c/ndbURkli/22-feedadapter-can-accept-encoded-episode-guid-s)

2016-12-28 22:36 UTC, alxjrvs commented on src/app/embed/adapters/feed.adapter.ts
> +let sha1 = require('sha1');
This was weird. I couldn't import it using the standard ES6 `import` strategy, but it worked with require. Wondering if it is a local setup issue.

2016-12-29 15:01 UTC, cqr requested changes

2016-12-29 15:01 UTC, chrisrhoden commented on src/app/embed/adapters/feed.adapter.ts
> +let sha1 = require('sha1');
does `import sha1 from 'sha1'` not work?

2016-12-29 15:01 UTC, chrisrhoden commented on src/app/embed/adapters/feed.adapter.ts
> +  private isEncrypted(guid): boolean {
I'd prefer we call this isEncoded.

2016-12-29 15:08 UTC, alxjrvs commented on src/app/embed/adapters/feed.adapter.ts
> +let sha1 = require('sha1');
Not on my system, no - "could not find module sha1".

2016-12-29 16:41 UTC, chrisrhoden commented on src/app/embed/adapters/feed.adapter.ts
> +let sha1 = require('sha1');
were you going to vendor that module I sent you? I really want to avoid requires since they don't do well with modern build system optimizations.

2016-12-29 16:49 UTC, alxjrvs commented
Yep! Not pushed up yet.

On Dec 29, 2016 11:41 AM, "Chris Rhoden" <notifications@github.com> wrote:

> *@chrisrhoden* commented on this pull request.
> ------------------------------
>
> In src/app/embed/adapters/feed.adapter.ts
> <https://github.com/RadioPublic/play.prx.org/pull/5>:
>
> > @@ -2,8 +2,10 @@ import { EMBED_FEED_URL_PARAM, EMBED_FEED_ID_PARAM, EMBED_EPISODE_GUID_PARAM } f
>  import {Injectable} from '@angular/core';
>  import { Http, Response } from '@angular/http';
>  import { Observable } from 'rxjs/Observable';
> -import { AdapterProperties, DataAdapter } from './adapter.properties'
> +import { AdapterProperties, DataAdapter } from './adapter.properties';
> +let sha1 = require('sha1');
>
> were you going to vendor that module I sent you? I really want to avoid
> requires since they don't do well with modern build system optimizations.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/RadioPublic/play.prx.org/pull/5>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAKq6Sy-3PXKd0kc-mgvDzgaR3Yowk_Uks5rM-LPgaJpZM4LXNcB>
> .
>

2016-12-29 17:44 UTC, alxjrvs commented
@chrisrhoden RFR

2016-12-29 19:47 UTC, cqr approved these changes

2016-12-29 19:47 UTC, merged